# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

services:

python:
  - "2.7"

before_install:
  - pwd
  - ls -a
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V

install:
  - pip install . -vvv

script:
  - python setup.py pytest
  - flake8 --show-source --statistics --config=.flake8
  - codecov

notifications:
  email:
    recipients:
      - andre@merzky.net
    on_success: change
    on_failure: always

after_success:

